server:
  servlet:
    context-path: /
  port: 8080
spring:
  application:
    name: myretail-service
  jpa:
    database: MYSQL
    show-sql: true
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/products
    username: root
    password: root@1234
    driverClassName: com.mysql.jdbc.Driver
    dbcp2:
      validation-query: Select 1
      test-while-idle: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: products
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
