server:
  servlet:
    context-path: /
  port: 8080
spring:
  application:
    name: myretail-service
  jpa:
    database: MYSQL
    show-sql: true
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/myretailservice
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  data:
    mongodb:
      uri: null
      username: null
      password: null